build:
  image: mcr.microsoft.com/dotnet/core/sdk:3.1
  script:
    - cd Kraken.Net
    - dotnet build Kraken.Net.csproj
    - dotnet pack Kraken.Net.csproj -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg -o .
    - dotnet nuget add source "$CI_SERVER_URL/api/v4/projects/$CI_PROJECT_ID/packages/nuget/index.json" --name gitlab --username gitlab-ci-token --password $CI_JOB_TOKEN --store-password-in-clear-text
    - dotnet nuget push "*.nupkg" --source gitlab
  artifacts:
    paths:
      - "./Kraken.Net/*.snupkg"